[package]
name = "project51"
version = "0.0.1"
authors = []
edition = "2018"

[dependencies.amethyst]
version = "0.15.0"
features = ["metal"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
guard = "0.5.0"
#quote = "=1.0.2"