[package]
name = "project51"
version = "0.0.1"
authors = []
edition = "2018"

[dependencies.amethyst]
version = "0.14.0"
features = ["metal"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
#quote = "=1.0.2"