brace_style = "PreferSameLine"
fn_args_layout = "Compressed"
fn_single_line = true
indent_style = "Visual"
trailing_comma = "Never"
reorder_impl_items = true
reorder_imports = true
overflow_delimited_expr = true
merge_imports = true
where_single_line = true
wrap_comments = true
max_width = 120
struct_lit_width = 36
unstable_features = true